import{a as L,S as E,i as n}from"./assets/vendor-Rdv7LHNr.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))p(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&p(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function p(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();L.defaults.baseURL="https://pixabay.com";async function w(r,e,s){return(await L("/api/",{params:{page:e,per_page:s,key:"45209949-5a312a82ff87c6973b888687f",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const h=document.querySelector(".form"),f=document.querySelector(".images-list"),m=document.querySelector(".loader"),g=document.querySelector(".loader-more"),y=document.querySelector(".input"),a=document.querySelector(".btn-more");async function b(r){const e=await r.map(s=>`<li class="images-item">
        <a class="gallery-link" href="${s.largeImageURL}">
          <img
            class="gallery-image"
            src="${s.webformatURL}"
            alt="${s.tags}"

          />
          <div class="property">
          <p><span class="weight">Likes</span> ${s.likes}</p>
          <p><span class="weight">Views</span> ${s.views}</p>
          <p><span class="weight">Comments</span> ${s.comments}</p>
          <p><span class="weight">Downloads</span> ${s.downloads}</p>
          </div>
        </a>
      </li>`).join("");m.classList.remove("loader-open"),g.classList.remove("loader-more-open"),f.insertAdjacentHTML("beforeend",e),new E(".images-list a",{captionsData:"alt",captionDelay:250}).refresh()}async function S(r){const s=r.getBoundingClientRect().height;window.scrollBy({top:s*2.2,behavior:"smooth"})}let l=15,c=1,i,d,v;h.addEventListener("submit",async r=>{if(r.preventDefault(),a.classList.remove("btn-more-open"),f.innerHTML="",m.classList.add("loader-open"),i!==y.value.trim()&&(c=1),i=y.value.trim(),h.reset(),!i){n.error({title:"Error",message:"Please enter a search query"}),m.classList.remove("loader-open"),a.classList.remove("btn-more-open");return}try{const e=await w(i,c,l);if(e.hits.length===0){m.classList.remove("loader-open"),a.classList.remove("btn-more-open"),n.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!"});return}if(await b(e.hits),a.classList.add("btn-more-open"),d=e.totalHits,v=Math.ceil(d/l),d<l)return a.classList.remove("btn-more-open"),n.info({position:"bottomRight",message:"We're sorry, but you've reached the end of search results."})}catch(e){n.error({title:"Error",message:`Something went wrong: ${e.message}`})}});a.addEventListener("click",async()=>{c+=1,a.classList.remove("btn-more-open"),g.classList.add("loader-more-open");try{const r=await w(i,c,l);if(await b(r.hits),c>=v||r.hits.length<l)return g.classList.remove("loader-more-open"),n.info({position:"bottomRight",message:"We're sorry, but you've reached the end of search results."});const e=f.querySelector(".images-item");S(e),a.classList.add("btn-more-open")}catch(r){n.error({title:"Error",message:`Something went wrong: ${r.message}`})}});
//# sourceMappingURL=index.js.map
